### ISSUE TITLE
The dataset you are used

### ISSUE THREAD

**Issue by chenglibo123** [anshulcgm/polygen#1]
I would like to contact the author of the Polygen replication regarding the dataset used.
Hello, I have greatly benefited from reviewing your code. Following your replicated code, I have set up an Anaconda virtual environment. However, I am hindered by not having access to the dataset you used during training. You seem to have processed a ShapeNet dataset, but I'm unsure which specific dataset it is and how it was processed. Would it be possible for you to share the data processing steps so that I can run the code using the processed data, or could you share the dataset itself? Thank you very much.

**Comment by anshulcgm** [comment]
Hi, sorry for the late response, I have not been checking my github recently. The dataset I had used was already downloaded on my school's compute cluster at the time. I believe you should be able to download it from this link:

https://huggingface.co/datasets/ShapeNet/ShapeNetCore 

Let me know if this helps!
